CODE USED TO GENERATE LISTING 1, TABLE 1, LISTING 2, TABLE 2 IN RESEARCH PAPER

Imports

In [1]:
import pandas as pd
import duckdb

Display Settings

In [2]:
pd.set_option('display.max_rows', 10)
pd.set_option('display.float_format', '{:.5f}'.format)

Listing 1 & Table 1

In [3]:
query = f"""
SELECT * 
FROM 'spy_mbo/processed/spy_mbo.parquet'
WHERE ts_event >= '2026-03-23 10:00:00' AND ts_event <= '2026-03-23 10:30:00'
"""
market_by_order_df = duckdb.sql(query).df()
market_by_order_df

,ts_event,rtype,publisher_id,instrument_id,action,side,price,size,channel_id,order_id,flags,ts_in_delta,sequence,symbol,ts_recv
0,2026-03-23 10:00:00.000344-04:00,160,43,15144,A,B,660.19000,18,0,284773571068696,128,199366,23939758,SPY,2026-03-23 10:00:00.000551-04:00
1,2026-03-23 10:00:00.000353-04:00,160,43,15144,A,A,660.23000,16,0,284773571068705,128,199407,23939759,SPY,2026-03-23 10:00:00.000560-04:00
2,2026-03-23 10:00:00.000560-04:00,160,5,15144,A,A,660.23000,80,23,3191404863773174854,128,32762,21228992,SPY,2026-03-23 10:00:00.000592-04:00
3,2026-03-23 10:00:00.000572-04:00,160,15,15144,A,A,660.23000,80,0,860838092,128,0,105650931,SPY,2026-03-23 10:00:00.000584-04:00
4,2026-03-23 10:00:00.000624-04:00,160,2,15144,T,A,660.20000,100,0,0,0,166466,305195009,SPY,2026-03-23 10:00:00.000791-04:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9752969,2026-03-23 10:29:59.990853-04:00,160,2,15144,C,B,660.98000,40,0,819098584,128,162881,439257443,SPY,2026-03-23 10:29:59.991016-04:00
9752970,2026-03-23 10:29:59.990983-04:00,160,8,15144,C,B,660.98000,40,23,3191404932498824872,128,27555,27322436,SPY,2026-03-23 10:29:59.991010-04:00
9752971,2026-03-23 10:29:59.990985-04:00,160,5,15144,C,B,660.98000,40,23,3191404863781869157,128,27343,29010720,SPY,2026-03-23 10:29:59.991012-04:00
9752972,2026-03-23 10:29:59.991034-04:00,160,5,15144,C,B,660.98000,10,23,3191404863781869158,128,29522,29010721,SPY,2026-03-23 10:29:59.991063-04:00
9752973,2026-03-23 10:29:59.993641-04:00,160,2,15144,A,A,661.00000,100,0,819098980,128,162841,439257586,SPY,2026-03-23 10:29:59.993804-04:00

Listing 2 & Table 2

In [4]:
# consider the order lifecycle of the SPY ETF limit order with order_id = 861805602
query = f"""
SELECT * 
FROM 'spy_mbo/processed/spy_mbo.parquet'
WHERE order_id = 861805602
"""
order_861805602_lifecycle = duckdb.sql(query).df()
order_861805602_lifecycle

,ts_event,rtype,publisher_id,instrument_id,action,side,price,size,channel_id,order_id,flags,ts_in_delta,sequence,symbol,ts_recv
0,2026-03-23 10:00:01.896666-04:00,160,15,15144,C,B,660.14000,67,0,861805602,0,0,105764171,SPY,2026-03-23 10:00:01.896868-04:00
1,2026-03-23 10:00:01.896666-04:00,160,15,15144,F,B,660.14000,67,0,861805602,0,0,105764171,SPY,2026-03-23 10:00:01.896868-04:00
2,2026-03-23 10:00:01.896666-04:00,160,15,15144,F,B,660.14000,13,0,861805602,0,0,105764172,SPY,2026-03-23 10:00:01.896868-04:00
3,2026-03-23 10:00:01.896666-04:00,160,15,15144,C,B,660.14000,13,0,861805602,128,0,105764172,SPY,2026-03-23 10:00:01.896868-04:00
4,2026-03-23 10:00:01.896701-04:00,160,15,15144,A,B,660.14000,80,0,861805602,0,0,105764146,SPY,2026-03-23 10:00:01.896718-04:00